apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: false        # Отключаем привилегии
      runAsNonRoot: true       # Запрещаем запуск от root
      allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "64Mi"